name: Build and Test Application.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [linux-debug, linux-release, macos-debug, macos-release, windows-debug, windows-release]
        include:
          - build: linux-debug
            os: ubuntu-latest
            config: debug
          - build: linux-release
            os: ubuntu-latest
            config: release
          - build: macos-debug
            os: macos-latest
            config: debug
          - build: macos-release
            os: macos-latest
            config: release
          - build: windows-debug
            os: windows-latest
            config: debug
          - build: windows-release
            os: windows-latest
            config: release

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build  -c ${{ matrix.config }} --no-restore
    - name: Unit test
      run: dotnet test  -c ${{ matrix.config }} --no-build --verbosity normal
